version: '3'
services:
  mariadb:
    restart: always
    image: mariadb
    container_name: mariadb_godly
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MARIADB_ROOT_PASSWORD: godly_123456
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /usr/local/docker/mariadb/mariadb:/var/lib/mysql
      - /usr/local/docker/mariadb/conf:/etc/mysql
  redis:
    restart: always
    image: redis
    container_name: redis_godly
    ports:
      - 6379:6379
    volumes:
      - /usr/local/docker/redis/data:/data
      - /usr/local/docker/redis/conf/redis.conf:/etc/redis/redis.conf